# @package _global_

defaults:
  - base

robot:
  body_names: ['pelvis', 'torso', 'head', 'right_upper_arm', 'right_lower_arm', 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand', 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot']
  dof_names: ['abdomen_x', 'abdomen_y', 'abdomen_z', 'neck_x', 'neck_y', 'neck_z', 'right_shoulder_x', 'right_shoulder_y', 'right_shoulder_z', 'right_elbow_x', 'right_elbow_y', 'right_elbow_z', 'left_shoulder_x', 'left_shoulder_y', 'left_shoulder_z', 'left_elbow_x', 'left_elbow_y', 'left_elbow_z', 'right_hip_x', 'right_hip_y', 'right_hip_z', 'right_knee_x', 'right_knee_y', 'right_knee_z', 'right_ankle_x', 'right_ankle_y', 'right_ankle_z', 'left_hip_x', 'left_hip_y', 'left_hip_z', 'left_knee_x', 'left_knee_y', 'left_knee_z', 'left_ankle_x', 'left_ankle_y', 'left_ankle_z']

  # Observation parameters
  dof_obs_size: 72
  number_of_actions: 36
  self_obs_max_coords_size: 223  # ${eval:1+15*(3+6+3+3)-3}

  # Control parameters
  dof_body_ids: [1, 2, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14]
  joint_axis: ['xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz']

  key_bodies:
    - "right_hand"
    - "left_hand"
    - "right_foot"
    - "left_foot"
  non_termination_contact_bodies:
    - "right_foot"
    - "left_foot"

  right_foot_name: "right_foot"
  left_foot_name: "left_foot"
  head_body_name: "head"
  
  asset:
    robot_type: amp_humanoid
    asset_file_name: "mjcf/amp_humanoid.xml"
    usd_asset_file_name: "usd/amp_humanoid.usda"
