# @package _global_

robot:
  # Observation parameters
  dof_obs_size: ???
  number_of_actions: ???
  self_obs_size: ${.self_obs_max_coords_size}
  self_obs_max_coords_size: ???
  num_bodies: ${len:${.body_names}}
  contact_bodies: ${.body_names}

  # Control parameters
  body_names: ???  # DFS ordering
  dof_names: ???
  trackable_bodies_subset: ${.body_names}

  dof_body_ids: ???
  dof_effort_limits: null

  key_bodies: null
  non_termination_contact_bodies: null

  left_foot_name: ???
  right_foot_name: ???
  head_body_name: ???

  init_state: null

  contact_pairs_multiplier: 16

  num_key_bodies: ${len:${robot.key_bodies}}
  mimic_small_marker_bodies: null

  control:
    # Can be "built_in_pd" or "proportional"/"velocity"/"torque" for Proportional, Velocity, Torque control
    control_type: built_in_pd
    # PD Drive parameters:
    stiffness: null
    damping: null
    # action scale: target angle = actionScale * action + defaultAngle
    # only used in manual PD control
    action_scale: 1.0
    clamp_actions: 1.0

  asset:
    collapse_fixed_joints: null
    replace_cylinder_with_capsule: null
    flip_visual_attachments: null
    armature: null
    thickness: null
    max_angular_velocity: null
    max_linear_velocity: null
    density: null
    angular_damping: null
    linear_damping: null
    disable_gravity: null
    fix_base_link: null
    default_dof_drive_mode: 1  # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)

    robot_type: ???
    asset_file_name: ???
    usd_asset_file_name: ???
    asset_root: "protomotions/data/assets"
    self_collisions: True
    filter_ints: null

  sim:
    isaacgym:
      fps: 60
      decimation: 2
      substeps: 2
    isaaclab:
      fps: 120
      decimation: 4
    genesis:
      fps: 60
      decimation: 2
      substeps: 2

motion_lib:
  _target_: protomotions.utils.motion_lib.MotionLib
  motion_file: ${motion_file}
  ref_height_adjust: 0.
  fix_motion_heights: True
