# @package _global_

defaults:
  - base

robot:
  bfs_body_names: ???
  dfs_body_names: ['pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link', 'left_ankle_link', 'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link', 'torso_link', 'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link', 'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

  bfs_dof_names: ???
  dfs_dof_names: ['left_hip_yaw_joint', 'left_hip_roll_joint', 'left_hip_pitch_joint', 'left_knee_joint', 'left_ankle_joint', 'right_hip_yaw_joint', 'right_hip_roll_joint', 'right_hip_pitch_joint', 'right_knee_joint', 'right_ankle_joint', 'torso_joint', 'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']

  # Observation parameters
  dof_obs_size: ${eval:${len:${.dfs_dof_body_ids}}*6}
  number_of_actions: 19
  self_obs_max_coords_size: 298  # ${eval:1+20*(3+6+3+3)-3}

  # Control parameters
  dfs_dof_body_ids: [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 ]

  key_bodies: [ "left_ankle_link", "right_ankle_link", "left_elbow_link",  "right_elbow_link" ]
  non_termination_contact_bodies: [ "left_ankle_link", "right_ankle_link" ]
  right_foot_name: "right_ankle_link"
  left_foot_name: "left_ankle_link"

  init_state:
    pos: [ 0.0, 0.0, 1.0 ] # x,y,z [m]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_hip_yaw_joint: 0.
      left_hip_roll_joint: 0
      left_hip_pitch_joint: -0.4
      left_knee_joint: 0.8
      left_ankle_joint: -0.4
      right_hip_yaw_joint: 0.
      right_hip_roll_joint: 0
      right_hip_pitch_joint: -0.4
      right_knee_joint: 0.8
      right_ankle_joint: -0.4
      torso_joint: 0.
      left_shoulder_pitch_joint: 0.
      left_shoulder_roll_joint: 0
      left_shoulder_yaw_joint: 0.
      left_elbow_joint: 0.
      right_shoulder_pitch_joint: 0.
      right_shoulder_roll_joint: 0.0
      right_shoulder_yaw_joint: 0.
      right_elbow_joint: 0.

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 200
      hip_roll: 200
      hip_pitch: 200
      knee: 300
      ankle: 40
      torso: 300
      shoulder: 100
      elbow: 100
    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 5
      hip_roll: 5
      hip_pitch: 5
      knee: 6
      ankle: 2
      torso: 6
      shoulder: 2
      elbow: 2
    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 1.
    clamp_actions: 100.0

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    asset_file_name: "urdf/${robot.asset.robot_type}.urdf"
    robot_type: h1_no_head_no_hands
    self_collisions: False
    default_dof_drive_mode: 3

# Override motion lib default to use the adapted H1 variant
motion_lib:
  _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
env:
  config:
    simulator:
      sim:
        fps: 200 # 1/dt , dt = 0.005
        control_freq_inv: 4  # decimation
        substeps: 1

    mimic_reset_track:
      grace_period: 10